name: Gradle

on: [push, pull_request]

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [11]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts', 'gradle/wrapper/gradle-wrapper.properties', 'gradle.properties') }}
    - name: Cache pnpm packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.vaadin
          ~/.pnpm-store
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml', '**/package.json') }}
    - name: Build with Gradle
      run: ./gradlew clean build '-Pvaadin.productionMode' --stacktrace --info --no-daemon
    - name: Build the Docker image      
      run: docker build . --file Dockerfile --tag cloudapplicationmanager:$(date +%s)
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    #- name: Build and push
    #  uses: docker/build-push-action@v2
    #  with:
    #    context: .
    #    file: ./Dockerfile
    #    pull: true
    #    push: true
    #    cache-from: type=registry,ref=mlars0n/cloudapplicationmanager:latest
    #    cache-to: type=inline
    #    tags: cloudapplicationmanager:latest
